# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, upload_to='products', verbose_name='Картинка'),
        ),
    ]
